### ISSUE TITLE
[1.16.4] crashes on launch [Exception caught during firing event: tried to access field net.minecraft.client.gui.screen.BiomeGeneratorTypeScreens.field_239068_c_ ]

### ISSUE THREAD

**Issue by SDUBZ** [remplerus/SkyBlock#2]
forge:1.16.4-35.1.7
SB: SkyBlock-1.0

logs:
[latest.log](https://github.com/remplerus/SkyBlock/files/5622696/latest.log)
crash report:
[crash-2020-12-01_23.57.10-fml.txt](https://github.com/remplerus/SkyBlock/files/5622699/crash-2020-12-01_23.57.10-fml.txt)

**Comment by remplerus** [comment]
could you try the release here on github as curseforge currently doesnt accept fixes?
